### ISSUE TITLE
include example.env file in readme

### ISSUE THREAD

**Issue by yashsolanki22** [haardikk21/haardik.dev#1]
requesting to provide info on secret keys file to run the project on localhost i.e. example.env

**Comment by haardikk21** [comment]
@yashsolanki22 you can see the required things here - https://github.com/haardikk21/haardik.dev/blob/main/process.d.ts

the spotify refresh token is a bit annoying to get - see this blog post - https://leerob.io/blog/spotify-api-nextjs

**Comment by yashsolanki22** [comment]
Hi, @haardikk21 sorry! for the delayed response. I'll try to get the Spotify token and hopefully should work fine.
